platform:
    - x86

environment:
    global:
        CYG_ROOT: C:/cygwin
        CYG_MIRROR: http://cygwin.uib.no
        CYG_CACHE: C:/cygwin/var/cache/setup
    matrix:
        - 
            CYG_ARCH: x86

init:
    - 'echo System architecture: %PLATFORM%'

install:
    - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
    - 'appveyor DownloadFile http://ml.ignorelist.com/wodi/7/wodi32.tar.xz -FileName C:\wodi32.tar.xz'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P dos2unix -P diffutils -P cpio -P mingw64-i686-gcc-core -P mingw64-i686-gcc-g++ -P make -P git -P libncurses-devel -P m4 -P unzip >NUL'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P libmpfr-devel -P patch -P flexdll >NUL'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'
    - '%CYG_ROOT%/bin/bash -lc "mv /cygdrive/c/wodi32.tar.xz /tmp/wodi32.tar.xz && cd /tmp && rm -rf wodi32 && tar -xf wodi32.tar.xz && bash wodi32/install.sh"'

build_script:
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && ./appveyor-build.sh </dev/null"'
